const projects = [
  {
    id: "foodhutz-main",
    name: "FoodHutz Main Web Platform",
    category: "professional",
    badge: "Production Platform",
    featured: true,
    description:
      "Enterprise restaurant discovery and dining ecosystem serving customers across the UK. Designed with modular Next.js architecture, high-converting checkout, dynamic menus, and Sanity CMS integration.",
    highlights: [
      "Dynamic restaurant menus with Sanity headless CMS integration",
      "Redux Toolkit & RTK Query for client-side caching & fast state updates",
      "SSR & SEO architecture driving discoverability and organic search growth",
    ],
    stack: ["Next.js", "React", "Redux Toolkit", "RTK Query", "Sanity CMS", "Tailwind CSS"],
    sourceCode: "https://github.com/boniife",
    img: "/foodhutz-main.png",
    preview: "https://foodhutz.com",
  },
  {
    id: "foodhutz-reservation",
    name: "FoodHutz Reservations Engine",
    category: "professional",
    badge: "Production Platform",
    featured: true,
    description:
      "A high-availability table booking engine for multi-branch restaurants in the UK. Features custom interactive calendar logic, seat capacity limits, promotional discount codes, and instant confirmation flows.",
    highlights: [
      "Custom calendar scheduling logic with real-time seat availability",
      "Guest party size controls, time-slot allocation & discount engine",
      "Mobile-optimized progressive checkout flow with sub-second response",
    ],
    stack: ["Next.js", "Redux Toolkit", "RTK Query", "Tailwind CSS", "REST APIs"],
    sourceCode: "https://github.com/boniife",
    img: "/foodhutz-reservation.png",
    preview: "https://foodhutz.com/uk/reservation/london",
  },
  {
    id: "foodhutz-vendor",
    name: "FoodHutz Vendor Dashboard",
    category: "professional",
    badge: "Enterprise SaaS",
    featured: true,
    description:
      "Comprehensive merchant back-office portal enabling restaurant operators to manage digital menus, order streams, live table reservations, operational hours, and revenue metrics in real-time.",
    highlights: [
      "Real-time operational dashboard with dynamic tabular data and filters",
      "Granular menu management with allergen tags, pricing, and variants",
      "Complex form validation and authenticated role-based access",
    ],
    stack: ["Next.js", "Redux Toolkit", "RTK Query", "Tailwind CSS"],
    sourceCode: "https://github.com/boniife",
    img: "/foodhutz-vendor.png",
    preview: "https://vendoradmin.foodhutz.com/login",
  },
  {
    id: "foodhutz-oneclick",
    name: "FoodHutz OneClick Takeaway",
    category: "professional",
    badge: "Production Platform",
    description:
      "High-speed online takeaway food ordering platform engineered for maximum conversion, dynamic cart management, location-based pickup scheduling, and payment gateway connectivity.",
    highlights: [
      "Frictionless single-page ordering and cart management",
      "Performance-tuned Core Web Vitals for lightning-fast mobile loading",
      "Secure payment and delivery/pickup time selector integration",
    ],
    stack: ["Next.js", "Redux Toolkit", "RTK Query", "Tailwind CSS"],
    sourceCode: "https://github.com/boniife",
    img: "/foodhutz-oneclick.png",
    preview: "https://foodhutz.com/uk/takeaway/london",
  },
  {
    id: "foodhutz-microsites",
    name: "FoodHutz Brand Microsites",
    category: "professional",
    badge: "Multi-tenant Architecture",
    description:
      "Branded, SEO-driven restaurant microsites for partner dining chains within the FoodHutz network, offering custom branding, responsive layouts, and unified booking API connectivity.",
    highlights: [
      "Custom brand theming with reusable component libraries",
      "Direct integration with central reservation APIs",
      "High Lighthouse audit scores across performance and accessibility",
    ],
    stack: ["Next.js", "Sanity CMS", "Tailwind CSS"],
    sourceCode: "https://github.com/boniife",
    img: "/foodhutz-microsites.png",
    preview: "https://rootslebanese.foodhutz.co.uk/reservation",
  },
  {
    id: "xcursions",
    name: "Xcursions Luxury Travel Platform",
    category: "professional",
    badge: "Client Full-Stack",
    featured: true,
    description:
      "A premium travel booking and expedition web application allowing travellers to discover luxury getaways, manage itinerary dashboards, and pay for trips flexibly in installments.",
    highlights: [
      "Installment payment calculation engine and milestone tracking",
      "User dashboard with real-time countdowns and trip itinerary updates",
      "Interactive destination explorer with rich media galleries",
    ],
    stack: ["React", "Node.js", "Express", "MongoDB", "REST APIs"],
    sourceCode: "https://staging.xcursions.ng",
    img: "/xcursion.png",
    preview: "https://staging.xcursions.ng",
  },
  {
    id: "rccg-atlanta",
    name: "City Of David RCCG Atlanta",
    category: "professional",
    badge: "Client Web App",
    description:
      "Official community and digital portal for RCCG City of David, Atlanta branch. Features event schedules, community outreach, and secure Stripe-powered online donations and tithes.",
    highlights: [
      "Secure Stripe integration for recurring and one-time contributions",
      "Firebase database synchronization for announcements and events",
      "Fully responsive, mobile-first design system",
    ],
    stack: ["React", "Stripe API", "Firebase", "CSS3"],
    sourceCode: "https://github.com/justiniyke29/Joint-work",
    img: "/rccg.png",
    preview: "https://cod-dev.vercel.app/",
  },
  {
    id: "festival-of-sound",
    name: "Festival of Sound",
    category: "professional",
    badge: "Cultural Showcase",
    description:
      "Digital ticketing and exhibition platform showcasing African musical heritage and contemporary art, enabling attendee ticket reservations and artist exhibition booth bookings.",
    highlights: [
      "Next.js full-stack implementation with MongoDB storage",
      "Artist exhibition booth management and registration workflows",
      "Custom responsive styling built with modern Sass architecture",
    ],
    stack: ["Next.js", "Sass", "MongoDB", "Node.js"],
    sourceCode: "https://staging.festivalofsounds.com",
    img: "/festival.png",
    preview: "https://staging.festivalofsounds.com",
  },
  {
    id: "snapgram",
    name: "Snapgram Social Platform",
    category: "personal",
    badge: "Full-Stack App",
    description:
      "Feature-complete social media application connecting creators through photo sharing, infinite feeds, likes, saves, user profiles, and personalized content discovery.",
    highlights: [
      "Appwrite Backend-as-a-Service integration for authentication & storage",
      "Infinite scroll feed with optimistic UI updates and instant interactions",
      "Clean TypeScript architecture with Tailwind CSS styling",
    ],
    stack: ["Vite", "React", "Tailwind CSS", "Appwrite", "TypeScript"],
    sourceCode: "https://github.com/Boniife/boni-gram",
    img: "/snap.png",
    preview: "https://boni-gram.vercel.app/",
  },
  {
    id: "boni-youtube",
    name: "Boni-YouTube Media App",
    category: "personal",
    badge: "API-Driven App",
    description:
      "A fast YouTube alternative streaming client consuming RapidAPI endpoints, featuring category video filtering, custom video player, channel insights, and related recommendation feeds.",
    highlights: [
      "RapidAPI YouTube v3 endpoint consumption with cached requests",
      "Responsive video player with channel subscriber metrics & comments",
      "Instant category filtering and smart search queries",
    ],
    stack: ["React", "RapidAPI", "Node.js", "CSS3"],
    sourceCode: "https://github.com/Boniife/boniyoutube",
    img: "/youtube.png",
    preview: "https://storied-centaur-8e6c60.netlify.app/",
  },
  {
    id: "boni-fit",
    name: "Boni-Fit Workout Guide",
    category: "personal",
    badge: "Health & Fitness",
    description:
      "Interactive fitness and workout companion web application with curated exercise databases, muscle target filters, and video demonstrations sourced via fitness APIs.",
    highlights: [
      "Exercise library filterable by body part, muscle target, and equipment",
      "Integrated YouTube video demonstrations for correct lifting form",
      "Mobile-friendly quick reference during workout sessions",
    ],
    stack: ["React", "Tailwind CSS", "RapidAPI"],
    sourceCode: "https://github.com/Boniife/boni-fitness",
    img: "/fit.png",
    preview: "https://clinquant-stardust-ee5c74.netlify.app/",
  },
];

export default projects;
